apiVersion: v1
kind: Service
metadata:
  name: airflow-web
  namespace: dev
  labels:
    app: airflow
    component: web
    release: airflow
  annotations:
spec:
  selector:
    app: airflow
    component: web
    release: airflow
    namespace: dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer