apiVersion: v1
kind: Service
metadata:
  name: airflow-elb-web
  namespace: dev
  labels:
    app: airflow
    component: web
    release: airflow-dev
  annotations:
spec:
  selector:
    app: airflow
    component: web
    release: airflow-dev
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
