apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: airflow
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: airflow-dev
  chart:
    repository: https://marclamberti.github.io/airflow-eks-helm-chart
    name: airflow
    version: 6.9.4
  values:
    airflow:
        fernetKey: "zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI="
        extraEnv:
            - name: AIRFLOW__KUBERNETES__DAGS_IN_IMAGE
              value: "True"
            - name: AIRFLOW__KUBERNETES__NAMESPACE
              value: "dev"
            - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY
              value: "953076219999.dkr.ecr.eu-west-3.amazonaws.com/airflow-eks-docker"
            - name: AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG
              value: "90bc3f07"
        executor: Kubernetes
        image:
            repository: 953076219999.dkr.ecr.eu-west-3.amazonaws.com/airflow-eks-docker
            tag: 90bc3f07
    flower:
        enabled: false
    workers:
        enabled: false
    redis:
        enabled: false
    postgresql:
        persistence:
            enabled: true