apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dev-logs
  namespace: dev
  labels:
    app: airflow-dev
    release: airflow-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi